### ISSUE TITLE
Update b-tagging

### ISSUE THREAD

**Issue by hdelanno** [cms2l2v/2l2v_fwk#165]
This part of the code : https://github.com/cms2l2v/2l2v_fwk/blob/master/bin/hzz2l2v/runHZZ2l2vAnalysis.cc#L594-L612 should be updated for 76X (and also for 80X).
Furthermore, according to the b tagging convener, taking the value from the talk noted in github is not the good way to do.

I copy-paste here her answer:
"I am not sure how you would like to use the efficiencies and scale factors quoted in that presentation(NB: the one quoted in github) . Please note that these numbers are not the final ones for 74X, since there was an update at a later time [1] and even then there can be changes with respect to the official recommendation.

If you would like to use the scale factors to apply in an analysis, I refer you to the recommendation twiki:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation

If it is simply out of curiosity and not to be used in any way, you can have a look at the numbers for the same method in the AN for 76X [2].

Cheers,
Petra

[1] https://indico.cern.ch/event/461807/contributions/1135727/attachments/1187487/1722449/btagSF_ttbar2015_11_16.pdf
[2] http://cms.cern.ch/iCMS/user/noteinfo?cmsnoteid=CMS%20AN-2016/036
----> In particular see section 5.4 and Table 19"

**Comment by quertenmont** [comment]
lol...
I bet that all these came after Morriond ;-)

2016-06-10 10:26 GMT+02:00 Hugo Delannoy <notifications@github.com>:

> This part of the code :
> https://github.com/cms2l2v/2l2v_fwk/blob/master/bin/hzz2l2v/runHZZ2l2vAnalysis.cc#L594-L612
> should be updated for 76X (and also for 80X).
> Furthermore, according to the b tagging convener, taking the value from
> the talk noted in github is not the good way to do.
>
> I copy-paste here her answer:
> "I am not sure how you would like to use the efficiencies and scale
> factors quoted in that presentation(NB: the one quoted in github) . Please
> note that these numbers are not the final ones for 74X, since there was an
> update at a later time [1] and even then there can be changes with respect
> to the official recommendation.
>
> If you would like to use the scale factors to apply in an analysis, I
> refer you to the recommendation twiki:
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation
>
> If it is simply out of curiosity and not to be used in any way, you can
> have a look at the numbers for the same method in the AN for 76X [2].
>
> Cheers,
> Petra
>
> [1]
> https://indico.cern.ch/event/461807/contributions/1135727/attachments/1187487/1722449/btagSF_ttbar2015_11_16.pdf
> [2] http://cms.cern.ch/iCMS/user/noteinfo?cmsnoteid=CMS%20AN-2016/036
> ----> In particular see section 5.4 and Table 19"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/issues/165>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEbMyKi82SFfekrPAQrvYNAFWYyx43Xcks5qKR-_gaJpZM4Iyun7>
> .
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by hdelanno** [comment]
Solved here : https://github.com/cms2l2v/2l2v_fwk/pull/237
