### ISSUE TITLE
Lxbatch issues

### ISSUE THREAD

**Issue by vischia** [cms2l2v/2l2v_fwk#167]
Hi All,

I am having some issues when running on the lxbatch (which is the only feasible way for me at the moment, since it is the one that guarantees me a roughly constant and not too large runtime):

when I run my analysis (lepton + jets selection, and jets-only selection), W+Jets samples and data are processed correctly, whereas >90% of the ttbar jobs get killed by the system for excess CPU usage. 

I run on the 1nh queue, and I tried both the automatic splitting and to specify some very large splitting on my own, with the same result.

Did anyone have a similar problem? How did you solve it? 

When I was using the Spring15 samples, I had no problem whatsoever. 

Cheers,
Pietro

**Comment by vischia** [comment]
Hi,

did anyone have any similar problem with Lxbatch, or does anyone have an idea on why all of a sudden jobs started to hit the CPU limit?

One or two years ago multiple aodsim files were routinely loaded into memory at the same time, and this caused the memory to clog: can this be some similar effect? Did the recent changes to the framework touch this aspect?

Thanks in advance for any hint!

Cheers,
Pietro

**Comment by vischia** [comment]
Hi,

so, anybody with some kind of hint?

The repository is utterly unusable for me, right now :(

Cheers,
Pietro

**Comment by hdelanno** [comment]
Hi @vischia ,
I don't know if it is related, but did you test again the code since this PR #169 ?

Best,

Hugo

**Comment by vischia** [comment]
Hi @hdelanno ,

It is a while since I don't see the issue anymore, so I guess the PR worked somehow.

Closing this :)

Best,
Pietro
