### ISSUE TITLE
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale

### ISSUE THREAD

**Issue by xshi** [cms2l2v/2l2v_fwk#29]
Hello, 

When I try to run the third step, I found the following error: 

sh submit.sh 3 

Sample Interpolation         :...................................................
Plotting                     :...............................................Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
.Warning in <TH1F::Add>: Attempt to add histograms with different labels
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Warning in <TH1F::Add>: Attempt to add histograms with different labels
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 26 , nbins h2 =  30
Error in <TH1F::Divide>: Cannot divide histograms with different number of bins
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
.Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale
Error in <THistPainter::PaintInit>: Cannot set Y axis to log scale

Xin

**Comment by quertenmont** [comment]
> Error in THistPainter::PaintInit: Cannot set Y axis to log scale
is because the histogram has either negative or null maximum.
so log scale doesn't work.   The error is rather harmless.

The binning error is more important and we should identify which histogram has different binning.
In principle all histos should have the same binning among the samples, so that's a bit weird.

Loic

**Comment by xshi** [comment]
Just for record, @skeshri  also noticed a similar error:

Sample Interpolation         :..................................................
Plotting                     :...Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.136274)
Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.136274)
.............Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.179950)
Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.179950)
.....................Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.089048)
Error in <THistPainter::PaintInit>: log scale requested with a negative argument (-0.089048)
...........Warning in <TH1F::Add>: Attempt to add histograms with different labels
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 30 , nbins h2 =  26
Warning in <TH1F::Add>: Attempt to add histograms with different labels
Error in <TH1F::Add>: Attempt to add histograms with different number of bins : nbins h1 = 26 , nbins h2 =  30
Error in <TH1F::Divide>: Cannot divide histograms with different number of bins
