### ISSUE TITLE
Processing the photon+jet sample with the main runHZZ2l2vAnalysis 

### ISSUE THREAD

**Issue by xshi** [cms2l2v/2l2v_fwk#36]
Jobs has been submitted, will update once they are done.

**Comment by xshi** [comment]
Hi @georgia14  I have processed the photon sample, with some files not able to be processed. The output root file is saved at: 
/afs/cern.ch/user/x/xshi/public/plotter_2015_10_28.root 

Please let me know how to proceed. 

Also, for @quertenmont , what's the best way to re-submit the failed jobs? 

Thanks!
Xin

**Comment by quertenmont** [comment]
You can do submit.sh 1 --resubmit
(if you have not changed json file in the meanwhile)


Loic

2015-10-30 20:57 GMT+01:00 Xin Shi <notifications@github.com>:

> Hi @georgia14 <https://github.com/georgia14> I have processed the photon
> sample, with some files not able to be processed. The output root file is
> saved at:
> /afs/cern.ch/user/x/xshi/public/plotter_2015_10_28.root
>
> Please let me know how to proceed.
>
> Also, for @quertenmont <https://github.com/quertenmont> , what's the best
> way to re-submit the failed jobs?
>
> Thanks!
> Xin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/issues/36#issuecomment-152636768>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by xshi** [comment]
thanks Loic! I just resubmitted with $ ./submit.1.1 --resubmit.

**Comment by xshi** [comment]
Update: after two rounds of resubmit, all the files are processed correctly. Now, the plotter file is updated in the same location: 
/afs/cern.ch/user/x/xshi/public/plotter_2015_10_28.root
