### ISSUE TITLE
Electron ID scale factors for runD

### ISSUE THREAD

**Issue by vischia** [cms2l2v/2l2v_fwk#37]
Hi,

is anyone interested in the scale factors for the full electron isolation computed by the SUSY group?
https://indico.cern.ch/event/370511/contribution/3/attachments/1168717/1687113/tnP_EGM_Oct_12.pdf

I was thinking about giving them a try, labeling them as "susyloose", ... "susytight": I would not set them as default for now.

Is it OK for everybody?

Cheers,
Pietro

**Comment by quertenmont** [comment]
Go ahead Pietro!

Loic

2015-10-29 12:30 GMT+01:00 Pietro Vischia <notifications@github.com>:

> Hi,
>
> is anyone interested in the scale factors for the full electron isolation
> computed by the SUSY group?
>
> https://indico.cern.ch/event/370511/contribution/3/attachments/1168717/1687113/tnP_EGM_Oct_12.pdf
>
> I was thinking about giving them a try, labeling them as "susyloose", ...
> "susytight": I would not set them as default for now.
>
> Is it OK for everybody?
>
> Cheers,
> Pietro
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/issues/37>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/
