### ISSUE TITLE
Need to update the lumimask files 

### ISSUE THREAD

**Issue by xshi** [cms2l2v/2l2v_fwk#43]
Hi @georgia14, could you update the lumimasks files in the photon_sample.json? 

https://github.com/cms2l2v/2l2v_fwk/blob/master/test/hzz2l2v/photon_samples.json#L85-L89

Thanks!
Xin

**Comment by georgia14** [comment]
Hi Xin,
I just updated the lumimask filename as for the latest json file (v3) which is in hzz2l2v directory . Hope it is fine now , let me know in case . Thanks
