### ISSUE TITLE
MetFilter files added in my code for random triggers

### ISSUE THREAD

**Issue by vischia** [cms2l2v/2l2v_fwk#87]
Hi Loic,

I restarted finally to take a look at stuff.

I noticed that in my code have been added some events list for the MetFilter, but that such lists are stored in the data/MetFilter/ directory as files referring to double lepton triggers (looking at the filenames).

I use single lepton triggers for both single lepton and dilepton final state, so I think it should be incorrect to use such txt files that I suppose have been derived in a way somehow related to double lepton triggers.

How were those txt files computed? Do I actually care about including them in my code? I would just apply the MET filters from the POG flags. What are those lists about? In case I should actually care about those, how do I compute them for my single lepton triggers?

Thanks in advance!

Cheers,
Pietro

**Comment by quertenmont** [comment]
It comes from miniAOD twiki page.
Text file are provided by POGs because this avoided a rereco.
So POG computed the events that have to be filter out for some of the flags.
